In [1]:
import numpy as np


In [2]:
a = np.array([[1,2], [3,4]])
print(a)

[[1 2]
 [3 4]]


In [3]:
b = np.array([[3,7, 8], [10, 4, 5]])
print(b)

[[ 3  7  8]
 [10  4  5]]


In [7]:
#intakes rows to include column c = b[:1, :2]
c = b[:1]
print(c)

[[3 7 8]]


In [11]:
c = b[:, :2]
print(c)

[[ 3  7]
 [10  4]]


In [13]:
d = c * a
print(d)

[[ 3 14]
 [30 16]]


In [14]:
# @ for matrix multiplication
d = c @ a
print(d)

[[24 34]
 [22 36]]


In [16]:
# .identity is identity matrix
d = np.identity(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


<h2>Array Creation</h2>

<h2> Array Information</h2>

<h2>Array Manipulation</h2>

<h2>Indexing and Slicing</h2>

<h2>Statistical functions</h2>

<h2>Logical Operations</h2>

<h2> Linear Algebra</h2>